### ISSUE TITLE
Need help in running the system locally

### ISSUE THREAD

**Issue by rushabh-wadkar** [SuyashMore/AI-Proctored-Examination-System#2]
Backend server runs perfectly but the other servers (anomaly/test/result server) are not running locally.
Can you please help ? Need some steps to run this perfectly.

**Comment by SuyashMore** [comment]
I have mentioned the steps in readme .
can you paste the error you are facing

**Comment by rushabh-wadkar** [comment]
I am getting this error in running server.py insde `TestServer` dir and similarly for other servers too.

```
D:\proctoring-sys\AI-Proctored-Examination-System\AI-Proctored-Examination-System-main\src>python TestServer\server.py
Traceback (most recent call last):
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\oci\signer.py", line 53, in load_private_key
    return serialization.load_pem_private_key(secret, pass_phrase, backend=backend)
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\cryptography\hazmat\primitives\serialization\base.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1217, in load_pem_private_key
    return self._load_key(
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1448, in _load_key
    self._handle_key_loading_error()
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 1490, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TestServer\server.py", line 9, in <module>
    testFunc = testFunction()
  File "D:\proctoring-sys\AI-Proctored-Examination-System\AI-Proctored-Examination-System-main\src\TestServer\test_functions.py", line 6, in __init__
    self.db = dbManager()
  File "D:\proctoring-sys\AI-Proctored-Examination-System\AI-Proctored-Examination-System-main\src\TestServer\dbManager.py", line 10, in __init__
    self.at_provider = SignatureProvider(
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\borneo\iam\iam.py", line 191, in __init__
    self._provider = oci.signer.Signer(
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\oci\signer.py", line 253, in __init__
    self.private_key = load_private_key(private_key_content, pass_phrase)
  File "C:\Users\rusha\AppData\Local\Programs\Python\Python38\lib\site-packages\oci\signer.py", line 86, in load_private_key
    raise InvalidPrivateKey("The provided key is not a private key, or the provided passphrase is incorrect.")
oci.exceptions.InvalidPrivateKey: The provided key is not a private key, or the provided passphrase is incorrect.

```

**Comment by divyaagrwl** [comment]
I'm facing the exact same issue on my system as well, were you able to solve it?
